<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="lgvn14736" name="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider" tests="6" failures="0" timestamp="27 Jul 2018 07:23:40 GMT" time="62.469" errors="1">
  <testcase name="TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid" time="5.277" classname="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider"/>
  <testcase name="TC01_TC02_TC03_TC04_TC06_DataProvider_Valid" time="5.868" classname="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider"/>
  <testcase name="TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid" time="6.220" classname="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider"/>
  <testcase name="precondition" time="22.127" classname="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider"/>
  <testcase name="TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid" time="5.668" classname="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider"/>
  <testcase name="TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid" time="17.309" classname="Railway.TC01_TC02_TC03_TC04_TC06_DataProvider">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=int, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Involve TC04 - System shows message when user enter wrong password several times,(java.lang.String) pxq87yw@def.com,(java.lang.Integer) 4,(java.lang.String) 123,(java.lang.String) You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.,(java.lang.String) TC04 - Error message is not displayed as expected]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=int, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Involve TC04 - System shows message when user enter wrong password several times,(java.lang.String) pxq87yw@def.com,(java.lang.Integer) 4,(java.lang.String) 123,(java.lang.String) You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.,(java.lang.String) TC04 - Error message is not displayed as expected]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC01_TC02_TC03_TC04_TC06_DataProvider_Invalid -->
</testsuite> <!-- Railway.TC01_TC02_TC03_TC04_TC06_DataProvider -->
